name: logical_reasoning
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - cuda-cudart=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=12.8.55
  - cuda-runtime=12.1.0
  - cuda-version=12.8
  - ffmpeg=4.3
  - freetype=2.12.1
  - gcc_impl_linux-64=11.4.0
  - gcc_linux-64=11.4.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - gxx_impl_linux-64=11.4.0
  - gxx_linux-64=11.4.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.5
  - jpeg=9e
  - kernel-headers_linux-64=3.10.0
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.1.0.26
  - libcufft=11.0.2.4
  - libcufile=1.13.0.11
  - libcurand=10.3.9.55
  - libcusolver=11.4.4.55
  - libcusparse=12.0.2.55
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=11.4.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjpeg=12.1.1.14
  - libpng=1.6.39
  - libsanitizer=11.4.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=11.4.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.4.2
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - pillow=11.1.0
  - pip=25.0
  - pysocks=1.7.1
  - python=3.11.11
  - pytorch-cuda=12.1
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - sqlite=3.45.3
  - sysroot_linux-64=2.17
  - tbb=2021.8.0
  - tk=8.6.14
  - typing_extensions=4.12.2
  - urllib3=2.3.0
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - accelerate==1.4.0
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiohttp-cors==0.7.0
      - aiosignal==1.3.2
      - airportsdata==20241001
      - alignment-handbook==0.4.0.dev0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - astor==0.8.1
      - attrs==25.1.0
      - bitsandbytes==0.45.2
      - blake3==1.0.4
      - cachetools==5.5.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorful==0.5.6
      - compressed-tensors==0.9.1
      - datasets==3.3.1
      - deepspeed==0.15.4
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - evaluate==0.4.0
      - fastapi==0.115.8
      - filelock==3.17.0
      - flash-attn==2.7.4.post1
      - frozenlist==1.5.0
      - fsspec==2024.12.0
      - gguf==0.10.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.1
      - google-auth==2.38.0
      - googleapis-common-protos==1.67.0
      - grpcio==1.70.0
      - h11==0.14.0
      - hf-transfer==0.1.9
      - hjson==3.1.0
      - httpcore==1.0.7
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.29.0
      - importlib-metadata==8.6.1
      - iniconfig==2.0.0
      - interegular==0.3.3
      - jiter==0.8.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - lark==1.2.2
      - lm-format-enforcer==0.10.10
      - markdown==3.7
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - mistral-common==1.5.3
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - nest-asyncio==1.6.0
      - ninja==1.11.1.3
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.63.2
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python-headless==4.11.0.86
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.14.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.0.2
      - propcache==0.2.1
      - proto-plus==1.26.0
      - protobuf==3.20.2
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - py-spy==0.4.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybind11==2.13.6
      - pycountry==24.6.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2025.1
      - pyzmq==26.2.1
      - ray==2.42.1
      - referencing==0.36.2
      - regex==2024.11.6
      - responses==0.18.0
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.9
      - safetensors==0.5.2
      - scipy==1.15.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.45.3
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tiktoken==0.9.0
      - tokenizers==0.20.3
      - torch==2.6.0
      - torchaudio==2.5.1
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.46.0
      - triton==3.2.0
      - trl==0.12.0
      - tzdata==2025.1
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - virtualenv==20.29.2
      - vllm==0.7.2
      - wandb==0.19.7
      - watchfiles==1.0.4
      - websockets==15.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.28.post3
      - xgrammar==0.1.13
      - xxhash==3.5.0
      - yarl==1.18.3
      - zipp==3.21.0
