# Model arguments
model_name_or_path: NousResearch/Meta-Llama-3.1-8B-Instruct
model_revision: main
tokenizer_name_or_path: NousResearch/Meta-Llama-3.1-8B-Instruct
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_mixer:
  TongZheng1999/Meta-Llama-3.1-8B-Instruct_nl_rationale_1000_2048_3Rounds_round_1: 1.0
dataset_splits:
- train
auto_insert_empty_system_msg: false
preprocessing_num_workers: 12

# SFT trainer config
bf16: true
dataset_kwargs:
  add_special_tokens: false  # We already wrap <bos> and <eos> in the chat template
  append_concat_token: false # No need to add <eos> across samples
do_eval: false
eval_strategy: "no"
gradient_accumulation_steps: 16
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Meta-Llama-3.1-8B-Instruct-star-nl-2048-3Rounds-iter-1
hub_strategy: every_save
learning_rate: 5.0e-06
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 4096
max_steps: -1
num_train_epochs: 5
output_dir: /beacon-scratch/tongzh24//Meta-Llama-3.1-8B-Instruct/nl/2048_3Rounds/ft_iter_1
overwrite_output_dir: true
per_device_eval_batch_size: 4
per_device_train_batch_size: 1
push_to_hub: true
remove_unused_columns: true
report_to:
- tensorboard
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0
